# This script is originally generated by Gemini-2.0 Experimental Advanced
# With some minor optimizations
import math

import torch
import torch.nn.functional as F

from .logger import logger


class GaussianMixtureEM(object):
    def __init__(
        self,
        n_components,
        n_features,
        max_iter=100,
        tol=1e-7,
        learnable_covariance=False,
    ):
        self.n_components = n_components
        self.n_features = n_features
        self.max_iter = max_iter
        self.tol = tol
        self.learnable_covariance = learnable_covariance
        # Currently some related ops are not supported in ``mps`` mode, use cpus as
        # EM approaches are typically computationally light
        self.device = torch.device("cpu")

        # Initialize parameters
        self.weights = (
            torch.ones(n_components, device=self.device) / n_components
        )  # Mixture weights
        self.means = torch.randn(
            n_components, n_features, device=self.device
        )  # Component means
        self.covariances = torch.zeros(
            n_components, n_features, n_features, device=self.device
        )  # Component covariances

        # Initialize covariances to be diagonal (for simplicity, but you can make it full)
        for k in range(n_components):
            self.covariances[k] = torch.eye(n_features, device=self.device)

    def _e_step(self, X):
        """Expectation step: Calculate responsibilities."""
        n_samples = X.shape[0]
        log_responsibilities = torch.zeros(
            n_samples, self.n_components, device=self.device
        )

        for k in range(self.n_components):
            # Calculate the probability density of each data point under each Gaussian
            diff = X - self.means[k]
            exponent = -0.5 * torch.sum(
                (diff @ torch.inverse(self.covariances[k])) * diff, dim=1
            )
            log_det = torch.logdet(2 * math.pi * self.covariances[k])
            log_prob_density = exponent - 0.5 * log_det

            log_responsibilities[:, k] = torch.log(self.weights[k]) + log_prob_density

        # Normalize responsibilities so they sum to 1 for each data point
        responsibilities = F.softmax(log_responsibilities, dim=1)
        return responsibilities

    def _m_step(self, X, responsibilities):
        """Maximization step: Update parameters based on responsibilities."""
        n_samples = X.shape[0]
        effective_samples = torch.sum(responsibilities, dim=0)

        # Update weights
        self.weights = effective_samples / n_samples

        # Update means
        for k in range(self.n_components):
            self.means[k] = (
                torch.sum(responsibilities[:, k].view(-1, 1) * X, dim=0)
                / effective_samples[k]
            )

        if self.learnable_covariance:
            # Update covariances
            for k in range(self.n_components):
                diff = X - self.means[k]
                self.covariances[k] = (
                    diff.T @ (responsibilities[:, k].view(-1, 1) * diff)
                ) / effective_samples[k]
                # Regularization: Add a small value to the diagonal to ensure positive definiteness
                self.covariances[k] += 1e-6 * torch.eye(
                    self.n_features, device=self.device
                )

    def fit(self, X):
        """Fit the GMM to the data."""
        X = X.to(self.device)
        log_likelihood_history = []

        for iteration in range(self.max_iter):
            # E-step
            responsibilities = self._e_step(X)

            # M-step
            self._m_step(X, responsibilities)

            # Calculate log-likelihood for convergence check
            log_likelihood = self.compute_log_likelihood(X)
            log_likelihood_history.append(log_likelihood)

            # Check for convergence
            if (
                iteration > 0
                and torch.abs(log_likelihood_history[-1] - log_likelihood_history[-2])
                < self.tol
            ):
                logger.info(f"Converged after {iteration} iterations.")
                break

            if iteration == self.max_iter - 1:
                logger.warn(f"Reach maximum iterations: {iteration + 1}.")

        return log_likelihood_history

    def predict(self, X):
        """Predict the cluster assignments for new data."""
        X = X.to(self.device)
        responsibilities = self._e_step(X)
        return torch.argmax(responsibilities, dim=1)

    def compute_log_likelihood(self, X):
        """Compute the log-likelihood of the data under the current model."""
        n_samples = X.shape[0]
        log_likelihood = 0

        for k in range(self.n_components):
            diff = X - self.means[k]

            # More stable log determinant calculation
            log_det = torch.logdet(2 * math.pi * self.covariances[k])

            exponent = -0.5 * torch.sum(
                (diff @ torch.inverse(self.covariances[k])) * diff, dim=1
            )
            log_prob_density = exponent - 0.5 * log_det
            log_likelihood += torch.logsumexp(
                torch.log(self.weights[k]) + log_prob_density, dim=0
            )

        return log_likelihood / n_samples
